/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "bsp.h"

extern u8 DATA[];
extern char Send_Flag_Switch[2];
u8 flag=0,flag2=0;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Air_A", ID_BUTTON_0, 50, 50, 140, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Air_B", ID_BUTTON_1, 50, 190, 140, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Air_C", ID_BUTTON_2, 50, 330, 140, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Heater", ID_BUTTON_3, 250, 50, 141, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Light", ID_BUTTON_4, 250, 190, 140, 90, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Open", ID_BUTTON_5, 250, 330, 140, 90, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Temp", ID_TEXT_0, 480, 50, 62, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Hum", ID_TEXT_1, 480, 100, 55, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Temp", ID_TEXT_2, 480, 190, 62, 28, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hum", ID_TEXT_3, 480, 240, 53, 26, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Temp", ID_TEXT_4, 480, 330, 60, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hum", ID_TEXT_5, 481, 380, 52, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NULL", ID_TEXT_6, 550, 50, 111, 37, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NULL", ID_TEXT_7, 550, 100, 97, 35, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NULL", ID_TEXT_8, 550, 190, 105, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NULL", ID_TEXT_9, 550, 240, 125, 36, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NULL", ID_TEXT_10, 550, 330, 121, 31, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NULL", ID_TEXT_11, 550, 380, 141, 34, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "NULL", ID_TEXT_12, 650, 330, 121, 31, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "NULL", ID_TEXT_13, 650, 380, 141, 34, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
WM_HWIN AIRA;
WM_HWIN AIRB;
WM_HWIN AIRC;
WM_HWIN _Light;
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	u8 de;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Air_A'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Air_B'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Air_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Heater'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Light'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Open'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Temp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'Hum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'Temp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x0000FF00);
    //
    // Initialization of 'Hum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x0000FF00);
    //
    // Initialization of 'Temp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x00FF0000);
    //
    // Initialization of 'Hum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x00FF0000);
    //
    // Initialization of 'NULL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'NULL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'NULL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x0000FF00);
    //
    // Initialization of 'NULL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x0000FF00);
    //
    // Initialization of 'NULL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x00FF0000);
    //
    // Initialization of 'NULL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x00FF0000);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x00F0F0F0);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextColor(hItem, 0x00F0F0F0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Air_A'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			if(AIRA==NULL)
				AIRA = AIR_A();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Air_B'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			if(AIRB==NULL)
				AIRB = AIR_B();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Air_C'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			if(AIRC==NULL)
				AIRC = AIR_C();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Heater'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				if(flag==0)
				{
					flag=1;
					DATA[30]=100;
				}
				else
				{
					flag=0;
					DATA[30]=0;
				}
				Send_Flag_Switch[0]=1;
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Light'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			if(_Light==NULL)
				_Light = Light();
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Open'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
							if(flag2==0)
							{
								flag2=1;
								DATA[31]=100;
							}
							else
							{
								flag2=0;
								DATA[31]=0;
							}
							Send_Flag_Switch[1]=1;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
